### ISSUE TITLE
A inquiry about the derivation of your paper

### ISSUE THREAD

**Issue by yuki011121** [GATECH-EIC/BNS-GCN#4]
May I ask how the steps outlined in the formula derivation on pages 14/15 of your  article :"BNS-GCN: EFFICIENT FULL-GRAPH TRAINING OF GRAPH CONVOLUTIONAL NETWORKS WITH PARTITION-PARALLELISM AND RANDOM BOUNDARY NODE SAMPLING" were derived using rectangular frames
![捕获](https://github.com/GATECH-EIC/BNS-GCN/assets/79966041/81e3ebf4-1fed-4491-a817-86c53659c426)

**Comment by chwan1016** [comment]
Thank you for your question. We observe that the first expected value in this box represents the variance of $\Sigma_{u}\frac{1}{p}P_{v,u}H_{u,*}W$. As $Var[X]=E[X^2]-E[X]^2$, we can derive the last equation in the box.

I was convinced that adding Eq. 7 could improve the clarity of this derivation but I forget the reasons :)  Let me know if you have any unaddressed question. Thanks!

**Comment by ch-wan** [comment]
Hi @yuki011121, thank you for exploring BNS-GCN.

 The first equation computes the mean square error (MSE) of the approximated aggregation. You may know that $MSE=Var+Bias^2$. As the approximation of BNS-GCN is unbiased, the MSE is determined by the variance of neighbors' embeddings. You may find [this page](https://en.wikipedia.org/wiki/Mean_squared_error#Mean) helpful.

Note that the above derivation depends on the assumption that the selected neighbors are sampled with replacement. This is almost true when the sampling rate $p$ is small, which matches the setting of our experiments.

The second equation has one typo. We missed a factor $\frac{1}{\|\mathcal{B}_i\|}$ for the second term in the bracket, which will be fixed in the next version of BNS-GCN (stay tuned for it!). The proof can be concluded by leveraging the property of variance $Var(X)=E[X^2]-E[X]^2$.

Hope you find the above response useful. Feel free to let me know if you have any unaddressed questions.

**Comment by ch-wan** [comment]
@yuki011121 I'm going to close this issue due to its inactivity. Please feel free to reopen it if the above response is not sufficient. Thanks.
