### ISSUE TITLE
A question about experiment results on paper

### ISSUE THREAD

**Issue by kcncoY** [GATECH-EIC/BNS-GCN#5]
Dear author of BNS-GCN:
In the Table 9 of this paper, I have questions about the parameters of Epoch Time and Epoch Comm. 
<img width="358" alt="image" src="https://github.com/GATECH-EIC/BNS-GCN/assets/141907407/4142c422-074c-4c8e-96f4-63ace5cf6e3d">
1) How to get the number of Epoch Comm? The experiment output has "memory stats", is it from this result? 
2) In the output of each epoch, there are multiple epoch times of each processor. Is the final epoch time the average time or take the maximum value? (Same question as Epoch Comm)
Thank you very much!

**Comment by ch-wan** [comment]
Hi @kcncoY, thank you for exploring BNS-GCN.

I'm confused by your first question because you are asking two completely different metrics :). `Comm` measures the communication time among workers, and `memory stats` reports the memory consumption of BNS-GCN. If you are asking how we measured the communication time, it is implemented in [this file](https://github.com/GATECH-EIC/BNS-GCN/blob/master/helper/timer/comm_timer.py), and you can find an example about its usage [here](https://github.com/GATECH-EIC/BNS-GCN/blob/6bf3c9190835c386b5c8cf46bef47bc83cca3882/helper/feature_buffer.py#L94). 

For correctly measuring the epoch time of BNS-GCN, please add `--no-eval` when you launch it. This ensures that  no other tasks is launched between the end and start of the timer. The printed epoch time should be consistent among all workers.

Let me know if you have any other questions. Thanks!

**Comment by kcncoY** [comment]
Thank you for your detailed answer！In the first question, I want to know the source of Epoch Comm (MB) rather than the communication time. 
<img width="457" alt="image" src="https://github.com/GATECH-EIC/BNS-GCN/assets/141907407/5f550004-2c91-4806-ba2c-52215368b0a4">

**Comment by ch-wan** [comment]
As I remember, we did not directly measure communication volume (CV). Instead, we handly computed these results based on the number of transferred nodes and their embedding dimension. We also checked if the computed CV of BNS-GCN matches the CV measured by `nvprof`. You may check [this document](https://developer.nvidia.com/blog/cuda-pro-tip-nvprof-your-handy-universal-gpu-profiler/) for understanding the usage of `nvprof`. Thanks.

**Comment by kcncoY** [comment]
My problem has been resolved. Thank you very much for your response!
